# For detailed configuration reference documentation, visit:
# https://supabase.com/docs/guides/local-development/cli/config

project_id = "Zendesk"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[api.tls]
enabled = false

[db]
port = 54332
shadow_port = 54330
major_version = 15

[studio]
enabled = true
port = 54333
api_url = "http://127.0.0.1"

[analytics]
enabled = true
port = 54337
vector_port = 54338
gcp_project_id = ""
gcp_project_number = ""
gcp_jwt_path = ""

[auth]
enabled = true
site_url = "http://localhost:3020"
additional_redirect_urls = [
    "https://ucbtpddvvbsrqroqhvev.supabase.co/auth/v1/callback",
    "http://localhost:3020/api/email-gmail/oauth-callback",
    "http://localhost:3020/api/integrations/gmail/callback",
    "http://localhost:3020",
    "http://localhost:3020/auth/callback",
    "http://127.0.0.1:54321/auth/v1/callback"
]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.external.google]
enabled = true
client_id = "env(NEXT_PUBLIC_GOOGLE_AUTH_CLIENT_ID)"
secret = "env(GOOGLE_AUTH_CLIENT_SECRET)"
redirect_uri = "http://localhost:3020/auth/callback"
skip_nonce_check = false
