name: Pre-deployment Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  verify-deployment:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run linting
      run: npm run lint
      
    - name: Type check
      run: tsc --noEmit
      
    - name: Run tests
      run: npm test
      
    - name: Verify build
      run: npm run verify-build

    - name: Check for undefined exports
      run: |
        ! find . -type f -name "*.ts" -o -name "*.tsx" | xargs grep -l "export.*undefined" 